openapi: 3.0.0
tags:
  - name: Categorias
    description: Operaciones relacionadas con categorias
paths:
  /categorias:
    get:
      tags:
        - Categorias
      summary: Obtiene el listado de categorias 
      responses:
        200:
          description: Listado de categorias 
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    idCategoria:
                      type: integer
                      example: 1
                    descripcion:
                      type: string
                      example: Entrantes
                    estado:
                      type: boolean
                      example: true
                    tipoCategoria:
                      type: string
                      example: 2
                    tipoCategoriaNombre:
                      type: string
                      example: Plato
                    totalCategorias:
                      type: integer
                      example: 1
        404:
          description: No se encontraron categorías de productos
        
        500:
           description: Error interno del servidor
           

  /categorias/registrar:
    post:
      tags:
        - Categorias
      summary: Registra un categoria
      description: Recuerda que para registrar una categoria en el sistema es necesario que todos los datos esten llenos y que el TipoCategoria se divide en 2 tipos de usuario Producto(1) y Plato(2) 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                descripcion:
                  type: string
                  example: Entrantes
                estado:
                  type: integer
                  example: true
                tipoCategoria:
                  type: integer
                  example: 1
      responses:
        201:
          description: Categoría registrada correctamente
         
        400:
          description: Error en los datos proporcionados
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      vacios:
                        type: string
                        example: Todos los campos son requeridos para registrar una categoría.
                      existe:
                        type: string
                        example: Ya existe una categoría con la descripción proporcionada        
        500:
          description: Error interno del servidor
          

  /categorias/{id}:
    put:
      tags:
        - Categorias
      summary: Actualiza una mesa por ID
      description: Recuerda que para actualizar una categoria en el sistema es necesario que todos los datos esten llenos y que el TipoCategoria se divide en 2 tipos de usuario Producto(1) y Plato(2) 
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la categoria
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  properties:
                    descripcion:
                      type: string
                      example: Entrantes
                    estado:
                      type: boolean
                      example: true
                    tipoCategoria:
                      type: integer
                      example: 1
                  required:
                    - descripcion
                    - estado
                    - tipoCategoria
            examples:
              categoria_completo:
                value:
                  descripcion: Entrantes
                  estado: true
                  tipoCategoria: 1
              categoria_incompleto:
                value:
                  descripcion: Entrantes
      responses:
        200:
          description: Categoría actualizada correctamente
        400:
          description: Error en los datos proporcionados
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      idCategoria:
                        type: string
                        example: La identificación debe ser un número entero válido.
                      existe:
                        type: string
                        example: Ya existe una categoría con la descripción proporcionada.
                      error:
                        type: string
                        example: No se pudo actualizar la categoría seleccionada
        404:
          description: No se encontró la categoría con la identificación proporcionada.
        500:
          description: Error interno del servidor

    delete:
      tags:
        - Categorias
      summary: Elimina una categoria por ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la categoria
          schema:
            type: integer
      responses:
        200:
          description: Categoria eliminada correctamente.
        400:
          description: Error en los datos proporcionados
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      idCategoria:
                        type: string
                        example: La identificación debe ser un número entero válido
                      categoriaEnProductos:
                        type: string
                        example: No se puede eliminar una categoría que está asociada a productos. Elimine los productos asociados primero.
                      error:
                        type: string
                        example: No se pudo eliminar la categoría seleccionada
        404:
          description: No se encontró la categoría con la identificación proporcionada
        500:
          description: Error interno del servidor.
